### ISSUE TITLE
Docker build fails on Apple M1

### ISSUE THREAD

**Issue by ericvennemeyer** [avimoondra/fishbowl#163]
**Hardware/Software**
MacBook Air (M1, 2020)
MacOS Monterey v12.5

**Problem**
When following the [local development instructions](https://github.com/avimoondra/fishbowl#local-development) in the readme, `docker-compose up` results in the following error while attempting to execute the `RUN yarn install --frozen-lockfile` command in the `actions-server` Dockerfile:

```
#0 17.72 gyp ERR! find Python 
#0 17.72 gyp ERR! find Python Python is not set from command line or npm configuration
#0 17.72 gyp ERR! find Python Python is not set from environment variable PYTHON
#0 17.72 gyp ERR! find Python checking if "python3" can be used
#0 17.72 gyp ERR! find Python - "python3" is not in PATH or produced an error
#0 17.72 gyp ERR! find Python checking if "python" can be used
#0 17.72 gyp ERR! find Python - "python" is not in PATH or produced an error
#0 17.72 gyp ERR! find Python 
#0 17.72 gyp ERR! find Python **********************************************************
#0 17.72 gyp ERR! find Python You need to install the latest version of Python.
#0 17.72 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 17.72 gyp ERR! find Python you can try one of the following options:
#0 17.72 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 17.72 gyp ERR! find Python   (accepted by both node-gyp and npm)
#0 17.72 gyp ERR! find Python - Set the environment variable PYTHON
#0 17.72 gyp ERR! find Python - Set the npm configuration variable python:
#0 17.72 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#0 17.72 gyp ERR! find Python For more information consult the documentation at:
#0 17.72 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 17.72 gyp ERR! find Python **********************************************************
#0 17.72 gyp ERR! find Python 
#0 17.72 gyp ERR! configure error 
#0 17.72 gyp ERR! stack Error: Could not find any Python installation to use
#0 17.72 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#0 17.72 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#0 17.72 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#0 17.72 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#0 17.72 gyp ERR! stack     at exithandler (node:child_process:408:5)
#0 17.72 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
#0 17.72 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#0 17.72 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#0 17.72 gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#0 17.72 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#0 17.72 gyp ERR! System Linux 5.10.124-linuxkit
#0 17.72 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#0 17.72 gyp ERR! cwd /usr/app/node_modules/utf-8-validate
#0 17.72 gyp ERR! node -v v16.17.0
#0 17.72 gyp ERR! node-gyp -v v9.0.0
#0 17.72 gyp ERR! not ok
------
failed to solve: executor failed running [/bin/sh -c yarn install --frozen
```

Googling the error, I found several posts from other users trying to run `yarn install` as a Docker command on Apple M1s who had the same issue. (See below for links to some examples.) I was able to solve the error, and a few that cropped up afterwards, by taking the following steps:

1. In the /actions-server Dockerfile, I added the line `RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*` just before `RUN yarn install --frozen-lockfile`
2. In the docker-compose.yaml file, I changed the `fishbowl-postgres` image to `postgres:latest`
3. Also in the docker-compose.yaml file, I changed the `fishbowl-graphql-engine` image to `fedormelexin/graphql-engine-arm64`

In a nutshell, I installed python3 during the build and updated to images that are known to support ARM processors for Postgres and GraphQL. Making the above changes allowed the Docker container build process to complete and the local server to start up. I'm able to view the Fishbowl start screen at `http://localhost:3000/`. However, when I click "Host Game" I get the following error page:

<img width="523" alt="Screen Shot 2022-09-12 at 6 00 57 PM" src="https://user-images.githubusercontent.com/82679637/189784677-09377fd6-c452-4fee-a0a7-9e74ef0071f8.png">

I also ran through the local development instructions on my other computer, a 2015 iMac with an Intel Core i5 processor, and was able to get the game running without any problems. So I'm pretty certain that an incompatibility with Apple M1 chips is the problem. Unfortunately I still haven't found a complete solution.

**Related Resources**
https://github.com/docker/getting-started/issues/231#issuecomment-1018641262
https://github.com/docker/getting-started/issues/124#issuecomment-817322208
Possibly useful context about why Python fails on M1 Macs:
https://levelup.gitconnected.com/why-your-python-version-or-other-apps-dont-work-on-the-apple-macbook-m1-416af07de57b
https://pythonspeed.com/articles/docker-build-problems-mac/

**Comment by dsuresh-ap** [comment]
I have this same issue, the `docker build` fails locally on my M1 Pro but works fine on Azure Pipelines (linux)
